params:
  seed: 42

  # environment wrapper clipping
  env:
    clip_observations: 5.0
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [512, 512, 256]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    # rnn:
    #   name: lstm
    #   units: 512
    #   layers: 2

  load_checkpoint: False
  load_path: ''

  config:
    name: franka_pouring
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: False
    normalize_value: False
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1
    normalize_advantage: False
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 200
    max_epochs: 100
    save_best_after: 3
    save_frequency: 4
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.001
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 64
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_length: 8
    bounds_loss_coef: 0.0001